version: 2
jobs:
  lint:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run: shellcheck mac


  test-laptop:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run:
          name: install bats
          command: |
            git clone https://github.com/bats-core/bats-core.git /tmp/bats
            cd /tmp/bats
            sudo ./install.sh /usr/local
      - run: bash ./mac


workflows:
  version: 2
  commit:
    jobs:
      - lint
      - test-laptop
